name: gonc
on: push

jobs:
  compile:
    name: Compile gonc
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Compile using clang
        run: make gonc
        env:
          CC: clang
